package fauzi.hilmy.quizmaps21.model;

import java.util.ArrayList;

public class WisataData {
    public static String[][] dataWisata = new String[][]{
            {"Pantai Losari", "http://cdn2.tstatic.net/travel/foto/bank/images/pantai-losari_20170819_102120.jpg", "-5.143620", "119.407482","Tidak sah rasanya jika berlibur ke tempat wisata di Makassar tanpa bernarsis ria mengunjungi Pantai Losari. Landmark terkenal dari Kota Daeng ini tak pernah sepi dari pengunjung. Keindahan sunsetnya tak pernah jemu dipandang. Saat malam hari, tempat ini menjadi pusat kuliner dengan sajian makanan enak seperti pisang epe, es kelapa, dan lainnya."},
            {"Pantai Akkarena","https://www.jejakpiknik.com/wp-content/uploads/2018/05/YukPegi-34g-Rekreasi-Keluarga-di-Pantai-Akkarena-Makassar-630x380.jpg","-5.172582","119.387313","Hamparan pasir dan laut jernih membuat Pantai Akkarena jadi tempat berlibur yang ideal. Tak hanya bermain air, kamu juga bisa mencoba kegiatan lain seperti outbound, air softgun, ATV, dan lain-lain. Pantai Akkarena semakin lengkap dengan hadirnya restoran dengan menu lokal maupun internasional. Lokasinya berada di Kawasan Metro Tanjung Bunga."},
            {"Trans Studio","https://tsm-makassar.com/admin/uploads/home/thumb/01.jpg","-5.158594","119.394653","Indoor Theme Park terbesar di Indonesia Timur ini menampilkan konsep layaknya di Hollywood era 1960-an. Tempat ini menyediakan 21 permainan yang seru dan menegangkan. Selain itu, di waktu tertentu juga ada pertunjukan teater maupun sirkus kelas dunia. Jika ingin berkunjung, langsung saja ke Jl. HM. Dg. Patompo – Metro Tanjung Bunga"},
            {"Air Terjun Bantimurung","https://i.ytimg.com/vi/pfqg6DmwJYQ/maxresdefault.jpg","-5.016106","119.684778","Objek wisata yang terletak di Kabupaten Maros ini menampilkan eksotisme air terjun andalan Sulawesi Selatan. Di sini pengunjung bisa melepas gerah dengan bermain air berkedalaman sebatas pinggang orang dewasa. Selain itu, kawasan ini juga terkenal sebagai gudangnya kupu-kupu cantik. Ada banyak titik dengan keindahan yang cocok untuk jadi latar belakang foto kamu."},
            {"Pulau Kayangan","http://infosulsel.com/wp-content/uploads/2018/03/PULAU.jpg","-5.113889","119.400278","Objek wisata ini menyajikan panorama bahari yang memukau. Meskipun ukurannya kecil, namun berbagai fasilitas telah tersedia di sini. Seperti kolam renang, kafe, restoran, bahkan wifi pun ada. Kamu bisa berkunjung melalui Dermaga Pulau Kayangan di Jalan Ujungpandang dengan waktu tempuh sekitar 10 menit saja."},
            {"Pulau Lae-lae","https://wisatalova.com/wp-content/uploads/2016/12/lae-lae-island.jpg","-5.137500","119.391944","Pesona bahari Makassar juga dimiliki oleh Pulau Lae-lae. Dari Dermaga Kayu Bangkoa, hanya butuh waktu sekitar 5-10 menit saja untuk bisa sampai ke sini. Aktivitas seru seperti snorkeling pun wajib dilakukan untuk menyapa ikan-ikan kecil dan lucu. Tak hanya itu, kamu juga bisa menyanyikan lagu reggae di Pantai Bob. Asyik, kan?"},
            {"Pulau Kodingareng Keke","http://1.bp.blogspot.com/-IFMvcpZDrco/UG2fmNbF72I/AAAAAAAAEA0/svgJ-7Yd62k/s1600/DSC03445.jpg","-5.105434","119.288892","Objek wisata tak berpenghuni ini menjadi tujuan wajib wisatawan saat berkunjung ke Makassar. Keindahan bawah lautnya selalu menggoda untuk dijelajahi, baik dengan diving maupun snorkeling. Selain itu letaknya cukup jauh dari hiruk pikuk perkotaan, sehingga pas untuk menghilangkan rasa penat. Kamu bisa mengunjunginya melalui Dermaga Kayu Bangkoa."},
            {"Pulau Kapoposang","https://media.travelingyuk.com/wp-content/uploads/2018/01/Pulau-Kapoposang-image-source.jpg","-4.701389","118.954167","Destinasi wisata ini sering dinobatkan sebagai lokasi diving terbaik di Sulawesi Selatan. Tak tanggung-tanggung, ada 14 spot yang bisa dijelajahi. Lupa bawa alatnya? Jangan khawatir, di sini tersedia penyewaannya kok. Selain itu, kamu juga bisa melihat habitat asli penyu sisik yang terancam punah. Pulau ini bisa dikunjungi melalui Pelabuhan Paotere dengan waktu tempuh sekitar 3 jam."},
            {"Pulau Samalona","https://static.keepo.me//keepo.me-Pulau-Samalona-1160x543.jpg","-5.125172","119.343346","Pulau ini merupakan salah satu destinasi wisata bahari terbaik di Makassar. Pemandangan bawah lautnya bahkan sering mendapat pujian dari wisatawan dunia. Kamu bisa menikmatinya dengan menyewa alat snorkeling maupun diving yang tersedia di sini. Jika ingin berkunjung, langsung saja ke Dermaga Kayu Bangkoa."},
            {"Rammang-rammang","https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Rammang-Rammang.jpg/448px-Rammang-Rammang.jpg","-4.925026","119.607540","Gugusan pegunungan kapur di Kabupaten Maros ini memiliki pesona yang tak kalah dari negara lain, seperti Cina ataupun Vietnam. Semakin indah dengan hamparan sawah hijau di tengah-tengahnya. Tak hanya itu, di sini kamu bisa menemukan objek wisata lain seperti Telaga Bidadari, Hutan Batu Kapur, dan Gua Telapak Tangan. Seru, kan?"},
            {"Air Terjun Takapala","https://media.travelingyuk.com/wp-content/uploads/2018/01/Air-Terjun-Takapala-image-source.jpg","-5.274659","119.856944","Keindahan alam di Malino memang patut untuk diacungi jempol. Salah satu objek wisatanya yang wajib dikunjungi adalah Air Terjun Takapala. Tempat ini terletak berdekatan dengan kebun teh di Malino Highland. Gemuruh dan percikan airnya bisa bikin otak jadi segar. Jika ingin melihatnya dari dekat, kamu juga bisa naik ke bukit batu melalui 1000 anak tangga."},
            {"Kebun Teh Malino Highland","http://blog.reservasi.com/wp-content/uploads/2017/02/kebun-teh-malino.jpg","-5.242538","119.905990","Kebun teh ini berlokasi di Kabupaten Gowa dan berada di ketinggian sekitar 1.200 mdpl. Hamparan tanaman hijau serta sejuknya udara bisa membuat kamu merasa segar kembali. Tidak jarang pula kawasan ini diselimuti oleh kabut. Di puncaknya terdapat sebuah kafe dengan nuansa jepang. Cocok untuk bersantai sembari meminum teh hangat."},
            {"Fort Rotterdam","https://media.travelingyuk.com/wp-content/uploads/2018/01/Benteng-Rotterdam-image-source.jpg","-5.1340608","119.4024912","Objek wisata di Makassar ini merupakan peninggalan zaman penjajahan yang wajib untuk dikunjungi. Letaknya berdekatan dengan Pantai Losari dan Pusat Oleh-oleh Somba Opu. Di dalamnya terdapat Museum Lagaligo yang berisikan koleksi barang tradisional di masa lampau. Keindahan arsitektur dan tamannya pun bisa menjadi spot swafoto kamu."},
            {"Benteng Somba Opu","http://1.bp.blogspot.com/-7pVwpLV6-Rc/VwycPk-4tVI/AAAAAAAAAFs/Jsvha7EaWLwvix4vJhXKAf3e8NvtgCiAwCK4B/s1600/P1070528.JPG","-5.1929106","119.3942647","Salah satu benteng terkuat di Indonesia ini dulunya juga berfungsi sebagai pusat perdagangan rempah-rempah. Di dalamnya terdapat rumah adat suku di Sulawesi Selatan dan meriam raksasa berumur ratusan tahun. Bahkan, gedung kantor VOC pun masih berdiri kokoh di sini. Objek wisata ini terletak di Jalan Dg. Tata."},
            {"Museum Balla Lompoa","https://www.jejakpiknik.com/wp-content/uploads/2018/05/Museum_Balla_Lompoa-630x380.jpg","-5.2068206","119.4505919","Objek wisata di Makassar ini merupakan peninggalan dari Kerajaan Gowa-Tallo yang terkenal. Rumah panggung besar terpampang dengan megah di sini. Sayangnya, tak sembarang orang yang bisa memasukinya. Untuk mengobati rasa penasaran, kamu bisa berkunjung ke museum yang berisi koleksi benda-benda kerajaan ini. Letaknya berada di Jalan K.H. Wahid Hasyim, Kabupaten Gowa."},
            {"Bugis Waterpark","https://www.hargatiket.net/wp-content/uploads/2018/07/Harga-Tiket-Masuk-Bugis-Waterpark.jpg","-5.1535087","119.4933317","Kehadiran Bugis Waterpark seolah menjadi penghilang gerah di tengah hangatnya Makassar. Meskipun kesannya modern, namun cita rasa lokal tetap dipertahankan dalam penamaan wahananya. Taman rekreasi air ini juga memiliki beragam permainan seru dan menantang. Objek wisata ini terletak di Perumahan Bukit Baruga Antang."},
            {"Gowa Discovery Park","https://i.ytimg.com/vi/FARDAPLWoOI/maxresdefault.jpg","-5.1921752","119.4059922","Gowa Discovery Park juga menyajikan wahana bermain air seru. Di dalamnya terdapat seluncuran tinggi yang bisa memacu adrenalin kamu. Letaknya pun berdekatan dengan Benteng Somba Opu. Tak hanya itu, dalam kawasan wisata di Makassar ini juga terdapat sebuah taman burung dengan sensasi layaknya di hutan Amazon. Pokoknya seru, deh!"},
            {"Pantai Galesong Utara","https://media.travelingyuk.com/wp-content/uploads/2017/11/Gazebo-sebagai-fasilitas-untuk-pengunjung-image-source-1.jpg","-5.2419821","119.3759756","Objek wisata ini berada di Kabupaten Takalar dengan waktu tempuh sekitar 1 jam dari Makassar. Di sini, kamu bisa memilih bermain air di pantai maupun kolam renang. Selain itu, ada juga penginapan serta wahana lain seperti outbound, ATV, dan motor cross. Paling pas dijadikan tujuan berlibur bersama keluarga."},
            {"Pulau Badi","https://sangkarrang.files.wordpress.com/2015/01/pulau-badi.jpg","-4.9669229","119.2779119","Ingin melihat pusat rehabilitasi terumbu karang? Keinginanmu bisa terealisasi di Pulau Badi. Keindahan destinasi wisata bahari Kabupaten Pangkep ini juga punya keindahan bawah laut. Kamu bisa bermain-main dengan biota laut seperti di film Finding Nemo. Penghuni lokalnya juga sangat ramah kepada pengunjung. Pulau ini bisa dikunjungi melalui Pelabuhan Paotere."},
            {"Bukit Kanari","https://4.bp.blogspot.com/-F5HPbdo6H3U/WcmA1VfbTPI/AAAAAAAACjE/w5EVSn3Ra7ExYnkxXDykfwyoAiaUyjllwCEwYBhgL/s1600/P9020035.JPG","-4.9195875","119.8817108","Suguhan pemandangan indah dari ketinggian bisa dinikmati dari Bukit Kanari. Lokasinya berada di Dusun Malaka, Kabupaten Maros. Di sini juga banyak hiasan-hiasan penunjang kegiatan swafoto kamu. Konon, pengunjung akan bertemu dengan jodohnya selepas dari tempat wisata di Makassar ini. Tertarik, mblo?"},
            {"Gua Mimpi Bantimurung","https://3.bp.blogspot.com/-eEig3hz0XgE/TtnK6IAzDhI/AAAAAAAAAck/aZ3ysZTh5c4/s1600/bantimurung+objek+wisata+terbaik+di+sulawesi+selatan.jpg","-4.7637539","119.2335384","Tempat ini berada dalam kawasan Taman Nasional Bantimurung. Keindahan bebatuan unik dan stalaktit yang alami menjadi suguhan utamanya. Pengunjung juga bisa merasakan sensasi menjelajah gua sambil membawa lampu petromaks seperti di film petualangan. Konon, berkunjung ke sini bisa membuat kamu mendapatkan jodoh. Mau coba?"},
            {"Hutan Pinus Bissoloro","http://tempatwisataindonesia.id/wp-content/uploads/2017/01/Hutan-Pinus-Mangunan.jpg","-5.3511721","119.558553","Hutan Pinus yang eksotis ini terletak di Desa Bissoloro, Kabupaten Gowa. Tempat wisata di Makassar ini sangat cocok untuk kamu yang ingin beraktivitas kemping. Pemandangan sunsetnya juga terlihat sangat menawan. Selain itu, tempat ini juga sering menjadi lokasi acara musik. Kapan lagi menikmati alunan musik di tengah hutan, kan?"},
            {"Lembah Hijau Malino","https://media.travelingyuk.com/wp-content/uploads/2018/01/Lembah-Hijau-Malino-image-source.jpg","-5.2389386","119.8606551","Lembah Hijau Malino juga bisa menjadi destinasi wisata yang seru selama di Makassar. Lokasinya terletak di Kabupaten Gowa. Terdapat ragam permainan seru dan menguji adrenalin. Salah satunya Sky Bike, yaitu wahana sepeda di ketinggian 30 meter. Ingin tinggal lebih lama? Ada persewaan tenda dan resort juga loh."},
            {"Monumen Mandala","https://i0.wp.com/dolandolen.com/wp-content/uploads/2016/02/Monumen-Mandala.jpg","-5.1377087","119.4119573","Monumen ini merupakan simbol dari momen pembebasan Irian Barat. Objek wisata ini terletak di Jalan Jend. Sudirman dan sekilar mirip Monas di Jakarta. Di dalamnya terdapat diorama dan replika baju perjuangan masyarakat Sulawesi Selatan. Dari ujung menara, kamu bisa melihat Kota Makassar dari ketinggian."},
            {"Pulau Lanjukang","https://www.yukpiknik.com/wp-content/uploads/2016/04/pulau-lanjukang.jpg","-4.9799822","119.0746427","Keindahan bahari sebagai tempat wisata di Makassar seolah tak ada habisnya. Pulau mungil bernama Lanjukang ini seringkali menjadi tempat persinggahan nelayan untuk istirahat. Hamparan terumbu karang yang masih asri juga bisa dinikmati di sini dengan snorkeling. Kamu bisa mengunjunginya melalui Pelabuhan Paotere."}
    };

    public static ArrayList<Wisata> getWisataMakassar(){
        Wisata wisata = null;
        ArrayList<Wisata> list = new ArrayList<>();
        for (int i = 0; i < dataWisata.length; i++){
            wisata = new Wisata();
            wisata.setNama(dataWisata[i][0]);
            wisata.setGambar(dataWisata[i][1]);
            wisata.setLati(Double.parseDouble(dataWisata[i][2]));
            wisata.setLongi(Double.parseDouble(dataWisata[i][3]));
            wisata.setDetail(dataWisata[i][4]);
            list.add(wisata);
        }
        return list;
    }
}
